version: "3.9"
services:
  frontend:
    build: .
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3050:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
